<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-21 14:06
=======
# Generated by Django 5.2 on 2025-04-22 09:15
>>>>>>> bad32a02db6e9749226952f34a9a6794817cfe25

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('FOOD', 'Food'), ('TRAN', 'Transport'), ('ENTR', 'Entertainment'), ('UTIL', 'Utilities'), ('OTHR', 'Other')], max_length=100)),
            ],
=======
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Limit",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("TRAN", "Transport"),
                            ("ENTR", "Entertainment"),
                            ("UTIL", "Utilities"),
                            ("OTHR", "Other"),
                        ],
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date"],
            },
>>>>>>> bad32a02db6e9749226952f34a9a6794817cfe25
        ),
    ]
