# Generated by Django 5.2 on 2025-04-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categoria',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAN', 'Transport'), ('ENTR', 'Entertainment'), ('UTIL', 'Utilities'), ('OTHR', 'Other')], max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limit'),
        ),
    ]
