# Generated by Django 5.2 on 2025-04-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_expense_categoria_alter_expense_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-fecha'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
    ]
