# Generated by Django 5.2 on 2025-04-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_expense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fecha',
            field=models.DateTimeField(auto_created=True, verbose_name='Date'),
        ),
    ]
