# Generated by Django 5.2 on 2025-04-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_expense_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True, verbose_name='date')),
                ('concepto', models.CharField(max_length=255, verbose_name='concept')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cuantity')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linea', to='main.expense', verbose_name='line')),
            ],
            options={
                'verbose_name': 'ExpenseLine',
                'verbose_name_plural': 'ExpenseLines',
            },
        ),
    ]
