# Generated by Django 5.2 on 2025-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expenselines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselines',
            name='fecha',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='date'),
        ),
    ]
